[package]
name = "imx8mp_kernel"
version = "0.1.0"
edition = "2024"

[lib]
path = "_src/rslib.rs"
crate-type = ["staticlib"]
test = false
doctest = false
bench = false

[profile.release]
panic = "abort"
opt-level = "s"

[dependencies]
paste = "1.0.15"
